# Comercio de Automoviles

## 1. Contexto de los datos

In [ ]:
# Importar librerias
import pandas as pd
import numpy as np
import streamlit as st
import plotly.express as px

In [45]:
# Lectura de Datos
car_data = pd.read_csv("C:/Users/jhoan/Escritorio/ACADEMICO/TRIPLE_TEN/CIENCIA_DE_DATOS/SPRINT_7/Proyecto/Comercio_de_autos/vehicles_us.csv")

car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  object
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   42258 non-null  object
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  object
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), object(7)
memory usage: 5.1+ MB

In [46]:
print("Muestra:\n")
car_data.sample(10)

Muestra:

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
13903,19500,2015.0,ram 2500,excellent,8.0,gas,124900.0,automatic,pickup,grey,NaN,2019-03-04,33
5107,18994,2015.0,ford mustang,excellent,4.0,gas,34382.0,automatic,coupe,NaN,NaN,2018-12-25,20
30260,16999,2008.0,jeep wrangler unlimited,good,6.0,gas,NaN,manual,SUV,black,1.0,2018-12-23,33
16927,10995,2013.0,chrysler town & country,excellent,6.0,gas,82610.0,automatic,mini-van,silver,NaN,2018-12-09,88
43273,14995,2014.0,ram 1500,excellent,NaN,gas,NaN,automatic,truck,white,1.0,2018-11-27,18
24602,4995,NaN,toyota 4runner,excellent,6.0,gas,262564.0,automatic,SUV,green,NaN,2018-12-20,23
34998,1995,2007.0,chevrolet impala,good,6.0,gas,NaN,automatic,sedan,red,NaN,2018-09-26,2
20283,11500,2006.0,jeep grand cherokee laredo,like new,6.0,gas,46200.0,other,SUV,white,1.0,2019-03-18,62
25718,3995,2009.0,nissan murano,good,6.0,gas,153176.0,automatic,wagon,NaN,NaN,2018-07-05,34
10225,15500,2008.0,chevrolet silverado 1500,excellent,8.0,gas,73900.0,automatic,truck,blue,1.0,2019-01-09,39

In [47]:
# Muestra Data Frame de 1000 registros para enseñar en el aplicativo
muestra = car_data.sample(1000)
muestra.head(5)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
36474,34900,2018.0,ram 2500,excellent,8.0,gas,10450.0,automatic,truck,white,1.0,2019-02-27,22
17772,13950,2012.0,jeep wrangler unlimited,good,6.0,gas,109791.0,automatic,wagon,orange,1.0,2018-11-04,18
2328,5300,2014.0,nissan versa,excellent,NaN,gas,65000.0,automatic,sedan,white,NaN,2018-08-23,27
12284,18900,2013.0,ford f250 super duty,excellent,8.0,gas,127118.0,automatic,truck,white,NaN,2019-04-08,36
17209,9999,NaN,kia soul,excellent,NaN,gas,67995.0,manual,wagon,grey,NaN,2018-09-23,37

## 2. Analisis de Datos

### 2.1 Distribuciones

In [48]:
# Cantidad de autos clasificados por color y tipo
total_color = car_data.groupby('paint_color')['type'].value_counts()
df_total_color = total_color.reset_index(name='car_count')
df_total_color

    paint_color       type  car_count
0         black        SUV       2220
1         black      sedan       1770
2         black      truck       1581
3         black     pickup        938
4         black      coupe        470
..          ...        ...        ...
137      yellow  hatchback          6
138      yellow    offroad          5
139      yellow   mini-van          4
140      yellow      other          2
141      yellow      wagon          2

[142 rows x 3 columns]

In [49]:
# Grafico de carros sugun su tipo, segmentados por colores
bar_plot = px.bar(
    df_total_color,
    x = 'type',
    y = 'car_count',
    labels = {
        'type': 'Tipo de automóvil',
        'car_count': 'Cantidad',
        'paint_color': 'Colores'
        },
    title = "Clasificacion de autos segun su tipo y color",
    color = 'paint_color',
    color_discrete_map={
        'black': 'black',
        'blue': 'blue', 
        'brown': 'brown',
        'custom': 'gray',  
        'green': 'green',
        'grey': 'gray',
        'orange': 'orange',
        'purple': 'purple',
        'red': 'red',
        'silver': 'silver',
        'white': 'lightgray', 
        'yellow': 'yellow'
    },
    width = 700,
    height = 400
)

bar_plot.show()

In [50]:
# Estandarizacion de la variable Odometer para graficar el histograma 
df_odometer = car_data.dropna(subset=['odometer'])
print(f"Valores nulos: {df_odometer['odometer'].isnull().sum()}")

Valores nulos: 0

In [51]:
# Histograma de la variable odometer clasificado por el tipo de combustible
hist_plot = px.histogram(
    df_odometer, 
    x = 'odometer', 
    labels = {'fuel': 'Tipo de Combustible'},
    title = f"Distribución de Kilometraje clasificado Tipo de Combustible", 
    color = 'fuel',
    color_discrete_map={
        'diesel': 'black',
        'hybrid': 'blue', 
        'electric': 'green',
        'gas': 'red',
        'other': 'lightgray'
    }, 
    marginal = "box", 
    width = 700, 
    height = 400
)
hist_plot.show()

In [52]:
# Calculo de Estadisticos de la variable Odometer
prom_odo = np.mean(df_odometer['odometer'])
med_odo = np.median(df_odometer['odometer'])
desv_odo = np.std(df_odometer['odometer'])
print("Media: {:.1f}".format(prom_odo))
print("Mediana: {:.1f}".format(med_odo))
print("Desviación: {:.1f}".format(desv_odo))

Media: 115553.5
Mediana: 113000.0
Desviación: 65093.9

### 2.2 Relacion de Variables

In [53]:
# Grafico de dispersion
disp_plot = px.scatter(
    car_data, 
    x = 'model_year', 
    y = 'price', 
    labels = {'model_year': 'Año de Modelo',
              'price': 'Precio',
              'transmission': 'Transmision'},
    color = 'transmission', 
    title = f"Dispersión Año de Modelo vs. Precio", 
    color_discrete_map={  
        'automatic': 'green',
        'manual': 'orange',
        'other': 'lightgray'},
    width = 700, 
    height = 400
)
disp_plot.show()

In [ ]:
# Calcular correlacion entre variables
correlacion = car_data['model_year'].corr(car_data['price'])
print(f"Correlación de Pearson: {correlacion*100:.2f} %")

Correlación de Pearson: 42.87 %